# This workflow is named "Build and Push Docker Image"
name: Build and Push Docker Image

# Triggers the workflow on push events to the "main" branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # This job needs permissions to write to GitHub Packages (GHCR)
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # GITHUB_TOKEN is automatically created by Actions
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # Tags the image with the short commit SHA
          # Example: ghcr.io/your-username/your-repo:a1b2c3d
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
